### ISSUE TITLE
Software Development Security (Epic)

### ISSUE THREAD

**Issue by thijsr1** [Wessel-a/LaaS#17]
- Secure Software (OWASP top 10)
- GDPR Compliant
- ISO27001 Compliant

**Acceptance Criteria:**
- [ ] Criteria 1: Describe the first acceptance criterion here.
- [ ] Criteria 2: Describe the second acceptance criterion here.
- [ ] Criteria 3: Describe additional criteria as needed.

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] Code is reviewed and approved.
- [ ] Necessary tests are written and pass.
- [ ] Documentation is updated, if applicable.
- [ ] Feature is deployed to the [environment name].
